name: Lobby_Plugin
version: '${project.version}'
main: lobby_plugin.lobby_plugin.Main
api-version: 1.18
description: Lobby Plugin

commands:
  deez:
    description: deez nuts für Schleggamann

  warp:
    description: Teleportiert zu bestimmten Warppunkt
