name: Lobby_Plugin
version: '${project.version}'
main: lobby_plugin.lobby_plugin.Main
api-version: 1.18
description: Lobby Plugin

commands:
  start:
    description: Startet das Spiel
    default: op

  deez:
    description: deez nuts für Schleggamann

  zevibuild:
    description: Zevi Buildrechte an/aus

