name: Lobby_Plugin
version: '${project.version}'
main: lobby_plugin.lobby_plugin.Main
api-version: 1.18
description: Lobby Plugin

commands:
  deez:
    description: deez nuts für Schleggamann

  invsee:
    description: Zeigt das Inventar eines anderen Spielers

  warp:
    description: Teleportiert dich zu einem Warppunkt

  createwarp:
    description: Erstellt einen Warppunkt

  deletewarp:
    description: Löscht einen Warppunkt
