name: Enderchest_plugin
version: '${project.version}'
main: enderchest_plugin.enderchest_plugin.main
api-version: 1.18
description: Enderchest
commands:
  enderchest:
    description: ruft die Enderchest auf
