name: Lobby_Plugin
version: '1.0-SNAPSHOT'
main: lobby_plugin.lobby_plugin.Main
api-version: 1.18
description: Lobby Plugin

commands:
  deez:
    description: deez nuts für Schleggamann

  zevibuild:
    description: Zevi Buildrechte an/aus

