name: Game_Plugin
version: '1.0-SNAPSHOT'
main: game.plugin.game_plugin.Main
api-version: 1.18
description: Plugin für das Minigame

commands:
  end:
    description: Beendet das Spiel

  start:
    description: Startet das Spiel

  build:
    description: Aktiviert/Deaktiviert das Bauen